### PR TITLE
Fix icinga 2 examples

### PR DESCRIPTION
**Pull request by thatsmydoing**
Fix wrong variable being used for $HOSTALIAS, not $HOSTNAME. Also, the host variables for state and output refer to service.

### CODE REVIEW

**Comment by hannseman** [comment]
Thanks for the PR! If I recall correctly specifying `host_name` is required when defining a host while `alias` is not. Maybe this could cause some confusion to people who have not defined `alias` in the host definition?  

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#host

Maybe we could add an example of an alternative configuration using the $HOSTALIAS?

**Comment by thatsmydoing** [comment]
The issue is not about whether we use `host_name` or `alias`, since in the configuration we actually refer to  `host.display_name`.

The problem is that the command definition does not specify HOSTNAME, but HOSTALIAS. It doesn't really matter which one we use, so long as it's the same between the script and the definition.

I chose to use HOSTALIAS because that's what the rest of the Icinga 2 notify command definitions used.

**Comment by mbassett** [comment]
This needs to be merged as the text on the main documentation is just plain wrong.

**Comment by mbassett** [comment]
actually, doesn't quite look right.

**Comment by mbassett** [comment]
#40

**Pull request closed without merging**
